# Variables
@contentType = application/json
@token = ikvwwqea5zikvasdfasdfwwqea5zi2swrTEEd
@quester_url = http://localhost:7600

##################### STATUS ######################################### 
GET {{quester_url}}/status  HTTP/1.1

